org: luxkas
service: tourControl-api

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-west-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  hello:
    handler: handler.status
    events:
      - httpApi:
          path: /
          method: get
