org: luxkas
service: tourControl-api

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-west-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  status:
    handler: src/functions/status.handler
    events:
      - httpApi:
          path: /status
          method: GET

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST
